/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#494454",
        "primary-fixed": "#e9ddff",
        "primary-container": "#a078ff",
        "on-tertiary-fixed": "#2c1700",
        "surface-container": "#211e27",
        "on-tertiary-container": "#3f2300",
        "on-surface-variant": "#cbc3d7",
        "tertiary-container": "#ca801e",
        "on-secondary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#4edea3",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#482900",
        "on-primary": "#3c0091",
        "on-secondary-container": "#00311f",
        "inverse-primary": "#6d3bd7",
        "surface-container-highest": "#37333d",
        "on-background": "#e7e0ed",
        "outline": "#958ea0",
        "on-primary-fixed": "#23005c",
        "tertiary": "#ffb869",
        "error": "#ffb4ab",
        "secondary": "#4edea3",
        "on-surface": "#e7e0ed",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary-fixed-variant": "#673d00",
        "surface-tint": "#d0bcff",
        "tertiary-fixed": "#ffdcbb",
        "background": "#15121b",
        "surface": "#15121b",
        "primary": "#d0bcff",
        "on-secondary": "#003824",
        "inverse-on-surface": "#322f39",
        "surface-variant": "#37333d",
        "primary-fixed-dim": "#d0bcff",
        "inverse-surface": "#e7e0ed",
        "on-secondary-fixed": "#002113",
        "surface-container-lowest": "#0f0d15",
        "surface-bright": "#3b3742",
        "tertiary-fixed-dim": "#ffb869",
        "surface-container-high": "#2c2832",
        "surface-dim": "#15121b",
        "on-error": "#690005",
        "surface-container-low": "#1d1a23",
        "secondary-container": "#00a572",
        "on-primary-fixed-variant": "#5516be",
        "error-container": "#93000a",
        "on-primary-container": "#340080",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "16px",
        "stack-sm": "8px",
        "container-padding-desktop": "40px",
        unit: "8px",
        gutter: "16px",
        "stack-lg": "32px",
        "container-padding-mobile": "20px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
