import React from 'react';

export default function DisclaimerScreen({ onAccept }) {
  const [agreed, setAgreed] = React.useState(false);

  return (
    <>
      <div className="fixed inset-0 z-0 blur-3xl opacity-30 grayscale pointer-events-none overflow-hidden">
        <div className="grid grid-cols-12 gap-8 p-container-padding-desktop">
          <div className="col-span-3 h-screen bg-surface-container-high rounded-lg" />
          <div className="col-span-9 space-y-stack-lg">
            <div className="h-64 bg-surface-container-highest rounded-xl" />
            <div className="grid grid-cols-3 gap-6">
              <div className="h-48 bg-surface-container-low rounded-lg" />
              <div className="h-48 bg-surface-container-low rounded-lg" />
              <div className="h-48 bg-surface-container-low rounded-lg" />
            </div>
          </div>
        </div>
      </div>

      <div className="fixed top-[-10%] left-[-10%] w-[50%] h-[50%] rounded-full aura-glow bg-primary-container pointer-events-none" />
      <div className="fixed bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full aura-glow bg-secondary-container pointer-events-none" />

      <div className="fixed inset-0 z-[100] flex items-center justify-center bg-background/60 backdrop-blur-sm p-gutter">
        <div className="w-full max-w-2xl rounded-lg flex flex-col overflow-hidden animate-[fadeIn_0.5s_ease]"
          style={{ background: 'rgba(21, 18, 27, 0.7)', backdropFilter: 'blur(24px)', border: '1px solid rgba(255, 255, 255, 0.08)', boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.8)' }}>

          <div className="p-8 pb-4 text-center">
            <div className="flex justify-center mb-stack-md">
              <div className="w-16 h-16 rounded-full bg-primary-container/20 flex items-center justify-center relative">
                <span className="material-symbols-outlined text-primary text-4xl pulse-orb">bubble_chart</span>
                <div className="absolute inset-0 rounded-full border-2 border-primary/30 animate-ping opacity-20" />
              </div>
            </div>
            <h1 className="text-display-lg text-on-surface mb-stack-sm tracking-tight font-bold">Important Notice</h1>
            <p className="text-body-lg text-on-surface-variant max-w-lg mx-auto">
              AIDA is an Empathetic Intelligence designed for supportive conversation and emotional awareness.
            </p>
          </div>

          <div className="px-8 pb-8 flex-1 overflow-y-auto max-h-[500px] space-y-stack-lg">

            <div className="bg-surface-container-low/50 p-6 rounded-lg border border-outline-variant/30">
              <div className="flex gap-4 items-start mb-4">
                <span className="material-symbols-outlined text-tertiary">info</span>
                <h3 className="text-headline-md text-on-surface leading-tight font-semibold">Clinical Disclaimer</h3>
              </div>
              <p className="text-on-surface-variant text-body-md leading-relaxed">
                AIDA is <span className="text-on-surface font-semibold underline decoration-tertiary/50">not a licensed therapist, medical professional, or crisis intervention service.</span> The responses provided are generated by artificial intelligence and should not replace professional medical advice, diagnosis, or treatment.
              </p>
            </div>

            <div className="space-y-stack-sm">
              <h4 className="text-label-caps text-outline px-2">Nigerian Emergency Support</h4>

              <details className="group bg-surface-container-low/50 rounded-lg border border-outline-variant/20 overflow-hidden">
                <summary className="flex items-center justify-between p-4 cursor-pointer hover:bg-white/5 transition-colors list-none">
                  <div className="flex items-center gap-4">
                    <span className="material-symbols-outlined text-secondary">emergency</span>
                    <span className="text-body-lg font-semibold">Crisis Hotlines</span>
                  </div>
                  <span className="material-symbols-outlined transition-transform group-open:rotate-180">expand_more</span>
                </summary>
                <div className="px-4 pb-4 pt-2 space-y-3">
                  <div className="flex items-center justify-between p-3 bg-background/40 rounded-lg border border-white/5">
                    <div>
                      <p className="text-label-caps text-outline">Mentally Aware Nigeria (MANI)</p>
                      <p className="text-on-surface font-semibold">0809 111 6264</p>
                    </div>
                    <a href="tel:08091116264" className="p-2 rounded-full bg-secondary/10 text-secondary hover:bg-secondary/20 transition-all active:scale-95">
                      <span className="material-symbols-outlined">call</span>
                    </a>
                  </div>
                  <div className="flex items-center justify-between p-3 bg-background/40 rounded-lg border border-white/5">
                    <div>
                      <p className="text-label-caps text-outline">Lagos State Emergency</p>
                      <p className="text-on-surface font-semibold">112 or 767</p>
                    </div>
                    <a href="tel:112" className="p-2 rounded-full bg-secondary/10 text-secondary hover:bg-secondary/20 transition-all active:scale-95">
                      <span className="material-symbols-outlined">call</span>
                    </a>
                  </div>
                </div>
              </details>

              <details className="group bg-surface-container-low/50 rounded-lg border border-outline-variant/20 overflow-hidden">
                <summary className="flex items-center justify-between p-4 cursor-pointer hover:bg-white/5 transition-colors list-none">
                  <div className="flex items-center gap-4">
                    <span className="material-symbols-outlined text-primary">psychology</span>
                    <span className="text-body-lg font-semibold">When to seek professional help?</span>
                  </div>
                  <span className="material-symbols-outlined transition-transform group-open:rotate-180">expand_more</span>
                </summary>
                <div className="px-4 pb-4 pt-2">
                  <ul className="space-y-2 text-on-surface-variant text-body-md">
                    <li className="flex items-start gap-2">
                      <span className="text-primary mt-1">•</span>
                      <span>If you are experiencing thoughts of self-harm or suicide.</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary mt-1">•</span>
                      <span>If your symptoms interfere with your ability to work or maintain relationships.</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary mt-1">•</span>
                      <span>If you are dealing with severe trauma or hallucinations.</span>
                    </li>
                  </ul>
                </div>
              </details>
            </div>

            <div className="flex items-start gap-4 p-4 rounded-lg bg-primary-container/5 border border-primary-container/10">
              <div className="pt-1">
                <input
                  id="agree-checkbox"
                  type="checkbox"
                  checked={agreed}
                  onChange={(e) => setAgreed(e.target.checked)}
                  className="w-5 h-5 rounded border-outline-variant bg-surface-container-highest text-primary-container focus:ring-primary-container focus:ring-offset-background transition-all cursor-pointer"
                />
              </div>
              <label htmlFor="agree-checkbox" className="text-body-md text-on-surface-variant cursor-pointer select-none">
                I confirm that I have read the disclaimer above and understand that AIDA is a supportive AI companion, not a replacement for clinical psychiatric or psychological care.
              </label>
            </div>
          </div>

          <div className="p-8 pt-4 bg-surface-container-low/30 flex gap-4">
            <button
              onClick={() => window.close()}
              className="flex-1 px-6 py-4 rounded-full border border-outline-variant text-on-surface-variant font-semibold hover:bg-white/5 transition-all active:scale-95"
            >
              Exit AIDA
            </button>
            <button
              disabled={!agreed}
              onClick={onAccept}
              className={`flex-1 px-6 py-4 rounded-full font-semibold transition-all relative overflow-hidden group ${
                agreed
                  ? 'bg-primary-container text-on-primary-container shadow-[0_0_20px_rgba(160,120,255,0.4)] hover:scale-[1.02] cursor-pointer'
                  : 'bg-primary-container text-on-primary-container opacity-50 cursor-not-allowed'
              }`}
            >
              <span className="relative z-10">I Understand & Agree</span>
              {agreed && (
                <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-300" />
              )}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
